"""
Static seed data constants.

Why this file exists:
  Separates bulky fixture data from seed orchestration logic for readability.
"""

from app.models.enums import BookingStatus, ListingStatus, PropertyType

# All demo accounts use this password (documented in README).
DEMO_PASSWORD = "password123"

CATEGORIES = [
  {"name": "Beachfront", "slug": "beachfront", "icon_key": "waves", "sort_order": 1},
  {"name": "Cabins", "slug": "cabins", "icon_key": "tree-pine", "sort_order": 2},
  {"name": "Amazing pools", "slug": "amazing-pools", "icon_key": "waves-ladder", "sort_order": 3},
  {"name": "OMG!", "slug": "omg", "icon_key": "sparkles", "sort_order": 4},
  {"name": "Lakefront", "slug": "lakefront", "icon_key": "sailboat", "sort_order": 5},
  {"name": "Trending", "slug": "trending", "icon_key": "flame", "sort_order": 6},
  {"name": "Desert", "slug": "desert", "icon_key": "sun", "sort_order": 7},
  {"name": "Countryside", "slug": "countryside", "icon_key": "tractor", "sort_order": 8},
  {"name": "Islands", "slug": "islands", "icon_key": "palmtree", "sort_order": 9},
  {"name": "Mansions", "slug": "mansions", "icon_key": "castle", "sort_order": 10},
]

AMENITIES = [
  {"name": "Wifi", "slug": "wifi", "icon_key": "wifi", "amenity_group": "essentials"},
  {"name": "Kitchen", "slug": "kitchen", "icon_key": "utensils", "amenity_group": "essentials"},
  {"name": "Free parking", "slug": "free-parking", "icon_key": "car", "amenity_group": "essentials"},
  {"name": "Air conditioning", "slug": "air-conditioning", "icon_key": "snowflake", "amenity_group": "essentials"},
  {"name": "Washer", "slug": "washer", "icon_key": "washing-machine", "amenity_group": "essentials"},
  {"name": "Dryer", "slug": "dryer", "icon_key": "wind", "amenity_group": "essentials"},
  {"name": "Dedicated workspace", "slug": "workspace", "icon_key": "laptop", "amenity_group": "essentials"},
  {"name": "TV", "slug": "tv", "icon_key": "tv", "amenity_group": "essentials"},
  {"name": "Pool", "slug": "pool", "icon_key": "waves-ladder", "amenity_group": "outdoor"},
  {"name": "Hot tub", "slug": "hot-tub", "icon_key": "bath", "amenity_group": "outdoor"},
  {"name": "BBQ grill", "slug": "bbq-grill", "icon_key": "flame", "amenity_group": "outdoor"},
  {"name": "Patio", "slug": "patio", "icon_key": "fence", "amenity_group": "outdoor"},
  {"name": "Beach access", "slug": "beach-access", "icon_key": "umbrella", "amenity_group": "outdoor"},
  {"name": "Fireplace", "slug": "fireplace", "icon_key": "flame-kindling", "amenity_group": "indoor"},
  {"name": "Gym", "slug": "gym", "icon_key": "dumbbell", "amenity_group": "indoor"},
]

USERS = [
  {
    "email": "sarah@example.com",
    "full_name": "Sarah Chen",
    "is_host": True,
    "is_superhost": True,
    "avatar_url": "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
  },
  {
    "email": "marco@example.com",
    "full_name": "Marco Rossi",
    "is_host": True,
    "is_superhost": True,
    "avatar_url": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
  },
  {
    "email": "yuki@example.com",
    "full_name": "Yuki Tanaka",
    "is_host": True,
    "is_superhost": False,
    "avatar_url": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200",
  },
  {
    "email": "emma@example.com",
    "full_name": "Emma Wilson",
    "is_host": True,
    "is_superhost": True,
    "avatar_url": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200",
  },
  {
    "email": "alex@example.com",
    "full_name": "Alex Johnson",
    "is_host": False,
    "is_superhost": False,
    "avatar_url": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
  },
  {
    "email": "jamie@example.com",
    "full_name": "Jamie Lee",
    "is_host": False,
    "is_superhost": False,
    "avatar_url": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200",
  },
  {
    "email": "chris@example.com",
    "full_name": "Chris Morgan",
    "is_host": False,
    "is_superhost": False,
    "avatar_url": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200",
  },
]

# Each listing references host email, category slug, amenity slugs, and image URLs.
LISTINGS = [
  {
    "host_email": "sarah@example.com",
    "category_slug": "beachfront",
    "title": "Oceanview Retreat with Private Deck",
    "description": "Wake up to Pacific sunsets from this bright coastal home. Steps from the beach with a wraparound deck perfect for morning coffee.",
    "property_type": PropertyType.HOUSE,
    "price_per_night": 28500,
    "cleaning_fee": 12000,
    "country": "United States",
    "city": "Malibu",
    "state": "California",
    "address": "123 Pacific Coast Hwy",
    "lat": 34.0259,
    "lng": -118.7798,
    "max_guests": 6,
    "bedrooms": 3,
    "beds": 4,
    "bathrooms": 2,
    "amenity_slugs": ["wifi", "kitchen", "free-parking", "air-conditioning", "patio", "beach-access"],
    "images": [
      "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=1200",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200",
    ],
  },
  {
    "host_email": "sarah@example.com",
    "category_slug": "trending",
    "title": "Modern Loft in the Mission",
    "description": "Stylish loft with exposed brick, chef's kitchen, and walkable to Valencia Street's best restaurants and murals.",
    "property_type": PropertyType.APARTMENT,
    "price_per_night": 19500,
    "cleaning_fee": 8500,
    "country": "United States",
    "city": "San Francisco",
    "state": "California",
    "address": "456 Valencia St",
    "lat": 37.7599,
    "lng": -122.4148,
    "max_guests": 4,
    "bedrooms": 2,
    "beds": 2,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "kitchen", "workspace", "washer", "dryer", "tv"],
    "images": [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200",
    ],
  },
  {
    "host_email": "marco@example.com",
    "category_slug": "trending",
    "title": "Historic Apartment near the Colosseum",
    "description": "Elegant Roman apartment with terracotta floors and a sunny balcony overlooking cobblestone streets.",
    "property_type": PropertyType.APARTMENT,
    "price_per_night": 16500,
    "cleaning_fee": 7000,
    "country": "Italy",
    "city": "Rome",
    "state": "Lazio",
    "address": "Via dei Fori Imperiali 12",
    "lat": 41.8902,
    "lng": 12.4922,
    "max_guests": 4,
    "bedrooms": 2,
    "beds": 2,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "kitchen", "air-conditioning", "washer", "tv"],
    "images": [
      "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=1200",
      "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200",
    ],
  },
  {
    "host_email": "marco@example.com",
    "category_slug": "countryside",
    "title": "Tuscan Villa with Olive Grove",
    "description": "Stone villa surrounded by olive trees. Infinity pool, outdoor dining, and views of rolling hills.",
    "property_type": PropertyType.VILLA,
    "price_per_night": 42000,
    "cleaning_fee": 18000,
    "country": "Italy",
    "city": "Florence",
    "state": "Tuscany",
    "address": "Strada in Chianti 8",
    "lat": 43.7696,
    "lng": 11.2558,
    "max_guests": 10,
    "bedrooms": 5,
    "beds": 6,
    "bathrooms": 4,
    "amenity_slugs": ["wifi", "kitchen", "pool", "free-parking", "bbq-grill", "patio", "fireplace"],
    "images": [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200",
    ],
  },
  {
    "host_email": "yuki@example.com",
    "category_slug": "trending",
    "title": "Minimalist Studio in Shibuya",
    "description": "Compact, design-forward studio five minutes from Shibuya Crossing. Perfect for solo travelers or couples.",
    "property_type": PropertyType.APARTMENT,
    "price_per_night": 12500,
    "cleaning_fee": 4500,
    "country": "Japan",
    "city": "Tokyo",
    "state": "Tokyo",
    "address": "2-24-12 Shibuya",
    "lat": 35.6595,
    "lng": 139.7004,
    "max_guests": 2,
    "bedrooms": 1,
    "beds": 1,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "kitchen", "washer", "workspace"],
    "images": [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200",
    ],
  },
  {
    "host_email": "yuki@example.com",
    "category_slug": "cabins",
    "title": "Hakone Mountain Cabin",
    "description": "Traditional wooden cabin with onsen access nearby. Fireplace, tatami room, and forest views.",
    "property_type": PropertyType.CABIN,
    "price_per_night": 22000,
    "cleaning_fee": 9000,
    "country": "Japan",
    "city": "Hakone",
    "state": "Kanagawa",
    "address": "Motohakone 88",
    "lat": 35.2324,
    "lng": 139.1069,
    "max_guests": 4,
    "bedrooms": 2,
    "beds": 3,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "kitchen", "fireplace", "free-parking", "hot-tub"],
    "images": [
      "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=1200",
      "https://images.unsplash.com/photo-1518780664697-55e3ad9be603?w=1200",
    ],
  },
  {
    "host_email": "emma@example.com",
    "category_slug": "mansions",
    "title": "Georgian Townhouse in Notting Hill",
    "description": "Four-story townhouse on a pastel street. High ceilings, original moldings, and a private garden.",
    "property_type": PropertyType.HOUSE,
    "price_per_night": 55000,
    "cleaning_fee": 20000,
    "country": "United Kingdom",
    "city": "London",
    "state": "England",
    "address": "42 Portobello Rd",
    "lat": 51.5174,
    "lng": -0.2058,
    "max_guests": 8,
    "bedrooms": 4,
    "beds": 5,
    "bathrooms": 3,
    "amenity_slugs": ["wifi", "kitchen", "washer", "dryer", "fireplace", "workspace", "tv"],
    "images": [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200",
    ],
  },
  {
    "host_email": "emma@example.com",
    "category_slug": "countryside",
    "title": "Cotswolds Stone Cottage",
    "description": "Honey-colored stone cottage with rose garden. Fireplace, beamed ceilings, and village pub nearby.",
    "property_type": PropertyType.CABIN,
    "price_per_night": 18500,
    "cleaning_fee": 7500,
    "country": "United Kingdom",
    "city": "Bibury",
    "state": "Gloucestershire",
    "address": "Arlington Row",
    "lat": 51.7596,
    "lng": -1.8485,
    "max_guests": 4,
    "bedrooms": 2,
    "beds": 2,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "kitchen", "free-parking", "fireplace", "patio"],
    "images": [
      "https://images.unsplash.com/photo-1518780664697-55e3ad9be603?w=1200",
      "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=1200",
    ],
  },
  {
    "host_email": "sarah@example.com",
    "category_slug": "amazing-pools",
    "title": "Desert Oasis with Infinity Pool",
    "description": "Mid-century modern home in Joshua Tree with heated infinity pool and stargazing deck.",
    "property_type": PropertyType.HOUSE,
    "price_per_night": 35000,
    "cleaning_fee": 15000,
    "country": "United States",
    "city": "Joshua Tree",
    "state": "California",
    "address": "61231 Desert View Dr",
    "lat": 34.1347,
    "lng": -116.3131,
    "max_guests": 6,
    "bedrooms": 3,
    "beds": 3,
    "bathrooms": 2,
    "amenity_slugs": ["wifi", "kitchen", "pool", "free-parking", "bbq-grill", "hot-tub", "patio"],
    "images": [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200",
    ],
  },
  {
    "host_email": "marco@example.com",
    "category_slug": "lakefront",
    "title": "Lake Como Waterfront Villa",
    "description": "Private dock, sun terrace, and panoramic lake views. Boat rental available on request.",
    "property_type": PropertyType.VILLA,
    "price_per_night": 68000,
    "cleaning_fee": 25000,
    "country": "Italy",
    "city": "Como",
    "state": "Lombardy",
    "address": "Via Regina 22",
    "lat": 45.8081,
    "lng": 9.0852,
    "max_guests": 8,
    "bedrooms": 4,
    "beds": 5,
    "bathrooms": 3,
    "amenity_slugs": ["wifi", "kitchen", "pool", "free-parking", "patio", "gym"],
    "images": [
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200",
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200",
    ],
  },
  {
    "host_email": "emma@example.com",
    "category_slug": "islands",
    "title": "Santorini Cave House",
    "description": "Whitewashed cave house carved into the caldera cliff. Private plunge pool and Aegean sunset views.",
    "property_type": PropertyType.HOUSE,
    "price_per_night": 48000,
    "cleaning_fee": 16000,
    "country": "Greece",
    "city": "Oia",
    "state": "Santorini",
    "address": "Oia Caldera Path",
    "lat": 36.4618,
    "lng": 25.3753,
    "max_guests": 4,
    "bedrooms": 2,
    "beds": 2,
    "bathrooms": 2,
    "amenity_slugs": ["wifi", "kitchen", "pool", "patio", "air-conditioning"],
    "images": [
      "https://images.unsplash.com/photo-1570077186670-7d2c0c0c0c0c?w=1200",
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200",
    ],
  },
  {
    "host_email": "yuki@example.com",
    "category_slug": "desert",
    "title": "Kyoto Machiya Townhouse",
    "description": "Renovated traditional townhouse with interior garden. Walking distance to Gion district.",
    "property_type": PropertyType.GUESTHOUSE,
    "price_per_night": 24000,
    "cleaning_fee": 10000,
    "country": "Japan",
    "city": "Kyoto",
    "state": "Kyoto",
    "address": "Higashiyama-ku",
    "lat": 35.0037,
    "lng": 135.7788,
    "max_guests": 5,
    "bedrooms": 2,
    "beds": 3,
    "bathrooms": 2,
    "amenity_slugs": ["wifi", "kitchen", "washer", "workspace", "patio"],
    "images": [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200",
    ],
  },
  {
    "host_email": "sarah@example.com",
    "category_slug": "omg",
    "title": "Treehouse in the Redwoods",
    "description": "Elevated treehouse connected by suspension bridge. Floor-to-ceiling windows and outdoor shower.",
    "property_type": PropertyType.CABIN,
    "price_per_night": 32000,
    "cleaning_fee": 11000,
    "country": "United States",
    "city": "Santa Cruz",
    "state": "California",
    "address": "Redwood Forest Rd",
    "lat": 37.0502,
    "lng": -122.1085,
    "max_guests": 2,
    "bedrooms": 1,
    "beds": 1,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "kitchen", "free-parking", "patio"],
    "images": [
      "https://images.unsplash.com/photo-1449158743715-0a90ebb6d2d8?w=1200",
      "https://images.unsplash.com/photo-1518780664697-55e3ad9be603?w=1200",
    ],
  },
  {
    "host_email": "marco@example.com",
    "category_slug": "beachfront",
    "title": "Amalfi Coast Cliffside Apartment",
    "description": "Terraced apartment with lemon grove views and direct path to a private beach cove.",
    "property_type": PropertyType.APARTMENT,
    "price_per_night": 29500,
    "cleaning_fee": 12000,
    "country": "Italy",
    "city": "Positano",
    "state": "Campania",
    "address": "Via Positano 5",
    "lat": 40.6281,
    "lng": 14.4850,
    "max_guests": 4,
    "bedrooms": 2,
    "beds": 2,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "kitchen", "air-conditioning", "beach-access", "patio"],
    "images": [
      "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=1200",
      "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200",
    ],
  },
  {
    "host_email": "emma@example.com",
    "category_slug": "amazing-pools",
    "title": "Bali Jungle Villa with Pool",
    "description": "Open-air villa surrounded by rice terraces. Infinity pool, outdoor bathtub, and staff on call.",
    "property_type": PropertyType.VILLA,
    "price_per_night": 38000,
    "cleaning_fee": 14000,
    "country": "Indonesia",
    "city": "Bali",
    "state": "Bali",
    "address": "Jalan Raya Ubud",
    "lat": -8.5069,
    "lng": 115.2625,
    "max_guests": 6,
    "bedrooms": 3,
    "beds": 4,
    "bathrooms": 3,
    "amenity_slugs": ["wifi", "kitchen", "pool", "free-parking", "hot-tub", "bbq-grill", "gym"],
    "images": [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200",
    ],
  },
]

# Extra stays so each home carousel row (Tokyo / Bali / London / Rome / Malibu) feels full.
LISTINGS += [
  # --- Tokyo ---
  {
    "host_email": "yuki@example.com",
    "category_slug": "trending",
    "title": "Shinjuku Neon Capsule Loft",
    "description": "Compact designer loft above the neon. Perfect for solo travelers exploring Shinjuku nightlife.",
    "property_type": PropertyType.APARTMENT,
    "price_per_night": 9800,
    "cleaning_fee": 3500,
    "country": "Japan",
    "city": "Tokyo",
    "state": None,
    "address": "1-2-3 Shinjuku",
    "lat": 35.6938,
    "lng": 139.7034,
    "max_guests": 2,
    "bedrooms": 1,
    "beds": 1,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "workspace", "air-conditioning", "washer"],
    "images": [
      "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200",
      "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200",
    ],
  },
  {
    "host_email": "yuki@example.com",
    "category_slug": "omg",
    "title": "Asakusa Traditional Stay",
    "description": "Quiet room near Senso-ji with tatami seating and a peaceful courtyard.",
    "property_type": PropertyType.GUESTHOUSE,
    "price_per_night": 12500,
    "cleaning_fee": 4000,
    "country": "Japan",
    "city": "Tokyo",
    "state": None,
    "address": "2-3-4 Asakusa",
    "lat": 35.7148,
    "lng": 139.7967,
    "max_guests": 3,
    "bedrooms": 1,
    "beds": 2,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "kitchen", "air-conditioning"],
    "images": [
      "https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?w=1200",
      "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200",
    ],
  },
  {
    "host_email": "emma@example.com",
    "category_slug": "amazing-pools",
    "title": "Roppongi Skyline Suite",
    "description": "Floor-to-ceiling windows, skyline views, and walkable nightlife.",
    "property_type": PropertyType.APARTMENT,
    "price_per_night": 22000,
    "cleaning_fee": 8000,
    "country": "Japan",
    "city": "Tokyo",
    "state": None,
    "address": "6-10 Roppongi",
    "lat": 35.6628,
    "lng": 139.7314,
    "max_guests": 4,
    "bedrooms": 2,
    "beds": 2,
    "bathrooms": 2,
    "amenity_slugs": ["wifi", "kitchen", "air-conditioning", "washer", "dryer", "gym", "tv"],
    "images": [
      "https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1200",
      "https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=1200",
    ],
  },
  {
    "host_email": "sarah@example.com",
    "category_slug": "trending",
    "title": "Nakameguro Canal Apartment",
    "description": "Cherry-blossom canal views in spring; cafes and boutiques downstairs year-round.",
    "property_type": PropertyType.APARTMENT,
    "price_per_night": 16000,
    "cleaning_fee": 5500,
    "country": "Japan",
    "city": "Tokyo",
    "state": None,
    "address": "1-5 Nakameguro",
    "lat": 35.6441,
    "lng": 139.6988,
    "max_guests": 3,
    "bedrooms": 1,
    "beds": 2,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "kitchen", "washer", "workspace"],
    "images": [
      "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1200",
      "https://images.unsplash.com/photo-1528164344705-47542687000d?w=1200",
    ],
  },
  {
    "host_email": "marco@example.com",
    "category_slug": "mansions",
    "title": "Aoyama Designer Penthouse",
    "description": "Gallery-district penthouse with private terrace and curated interiors.",
    "property_type": PropertyType.APARTMENT,
    "price_per_night": 42000,
    "cleaning_fee": 15000,
    "country": "Japan",
    "city": "Tokyo",
    "state": None,
    "address": "3-1 Minami-Aoyama",
    "lat": 35.6652,
    "lng": 139.7121,
    "max_guests": 5,
    "bedrooms": 3,
    "beds": 3,
    "bathrooms": 2,
    "amenity_slugs": ["wifi", "kitchen", "air-conditioning", "washer", "dryer", "tv", "workspace", "gym"],
    "images": [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200",
    ],
  },
  # --- Bali ---
  {
    "host_email": "emma@example.com",
    "category_slug": "beachfront",
    "title": "Seminyak Surf Villa",
    "description": "Steps from the beach clubs. Open living, outdoor shower, and a private plunge pool.",
    "property_type": PropertyType.VILLA,
    "price_per_night": 29000,
    "cleaning_fee": 10000,
    "country": "Indonesia",
    "city": "Bali",
    "state": "Bali",
    "address": "Jalan Kayu Aya, Seminyak",
    "lat": -8.6913,
    "lng": 115.1682,
    "max_guests": 6,
    "bedrooms": 3,
    "beds": 4,
    "bathrooms": 3,
    "amenity_slugs": ["wifi", "kitchen", "pool", "free-parking", "beach-access", "bbq-grill"],
    "images": [
      "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200",
      "https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=1200",
    ],
  },
  {
    "host_email": "sarah@example.com",
    "category_slug": "amazing-pools",
    "title": "Canggu Rice-Field Bungalow",
    "description": "Sunrise over the paddies, coworking nearby, and a shared lagoon pool.",
    "property_type": PropertyType.HOUSE,
    "price_per_night": 15000,
    "cleaning_fee": 5000,
    "country": "Indonesia",
    "city": "Bali",
    "state": "Bali",
    "address": "Jalan Pantai Berawa",
    "lat": -8.6478,
    "lng": 115.1385,
    "max_guests": 4,
    "bedrooms": 2,
    "beds": 2,
    "bathrooms": 2,
    "amenity_slugs": ["wifi", "kitchen", "pool", "workspace", "free-parking"],
    "images": [
      "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200",
    ],
  },
  {
    "host_email": "marco@example.com",
    "category_slug": "islands",
    "title": "Uluwatu Cliff Pavilion",
    "description": "Dramatic cliff views, temple sunsets, and an infinity edge facing the ocean.",
    "property_type": PropertyType.VILLA,
    "price_per_night": 51000,
    "cleaning_fee": 18000,
    "country": "Indonesia",
    "city": "Bali",
    "state": "Bali",
    "address": "Pecatu, Uluwatu",
    "lat": -8.8291,
    "lng": 115.0849,
    "max_guests": 8,
    "bedrooms": 4,
    "beds": 5,
    "bathrooms": 4,
    "amenity_slugs": ["wifi", "kitchen", "pool", "hot-tub", "free-parking", "bbq-grill", "beach-access"],
    "images": [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d36b3d?w=1200",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1200",
    ],
  },
  {
    "host_email": "yuki@example.com",
    "category_slug": "countryside",
    "title": "Ubud Bamboo Nest",
    "description": "Eco bamboo nest in the jungle canopy with outdoor bathtub and bird song.",
    "property_type": PropertyType.CABIN,
    "price_per_night": 11000,
    "cleaning_fee": 4000,
    "country": "Indonesia",
    "city": "Bali",
    "state": "Bali",
    "address": "Penestanan, Ubud",
    "lat": -8.5035,
    "lng": 115.2441,
    "max_guests": 2,
    "bedrooms": 1,
    "beds": 1,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "patio", "free-parking"],
    "images": [
      "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200",
      "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1200",
    ],
  },
  {
    "host_email": "emma@example.com",
    "category_slug": "beachfront",
    "title": "Sanur Family Garden Home",
    "description": "Calm east-coast beach town. Walled garden, kids' pool, and bikes included.",
    "property_type": PropertyType.HOUSE,
    "price_per_night": 17500,
    "cleaning_fee": 6000,
    "country": "Indonesia",
    "city": "Bali",
    "state": "Bali",
    "address": "Jalan Danau Tamblingan",
    "lat": -8.6902,
    "lng": 115.2630,
    "max_guests": 7,
    "bedrooms": 3,
    "beds": 4,
    "bathrooms": 3,
    "amenity_slugs": ["wifi", "kitchen", "pool", "free-parking", "washer", "tv"],
    "images": [
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200",
      "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=1200",
    ],
  },
  # --- London ---
  {
    "host_email": "emma@example.com",
    "category_slug": "trending",
    "title": "Shoreditch Warehouse Flat",
    "description": "Brick walls, mezzanine bedroom, and street-art energy outside the door.",
    "property_type": PropertyType.APARTMENT,
    "price_per_night": 19500,
    "cleaning_fee": 7000,
    "country": "United Kingdom",
    "city": "London",
    "state": None,
    "address": "14 Brick Lane",
    "lat": 51.5225,
    "lng": -0.0718,
    "max_guests": 3,
    "bedrooms": 1,
    "beds": 2,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "kitchen", "washer", "workspace", "tv"],
    "images": [
      "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200",
    ],
  },
  {
    "host_email": "sarah@example.com",
    "category_slug": "mansions",
    "title": "Chelsea Garden Townhouse",
    "description": "Elegant mews house with a private patio garden near the King's Road.",
    "property_type": PropertyType.HOUSE,
    "price_per_night": 48000,
    "cleaning_fee": 16000,
    "country": "United Kingdom",
    "city": "London",
    "state": None,
    "address": "8 Cadogan Place",
    "lat": 51.4942,
    "lng": -0.1580,
    "max_guests": 8,
    "bedrooms": 4,
    "beds": 5,
    "bathrooms": 3,
    "amenity_slugs": ["wifi", "kitchen", "washer", "dryer", "fireplace", "patio", "free-parking"],
    "images": [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200",
      "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=1200",
    ],
  },
  {
    "host_email": "marco@example.com",
    "category_slug": "omg",
    "title": "South Bank River View Studio",
    "description": "Thames views, Tate Modern walks, and a compact designer kitchen.",
    "property_type": PropertyType.APARTMENT,
    "price_per_night": 16500,
    "cleaning_fee": 5500,
    "country": "United Kingdom",
    "city": "London",
    "state": None,
    "address": "22 Upper Ground",
    "lat": 51.5074,
    "lng": -0.1080,
    "max_guests": 2,
    "bedrooms": 1,
    "beds": 1,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "kitchen", "air-conditioning", "tv", "workspace"],
    "images": [
      "https://images.unsplash.com/photo-1486299267070-83823f5448dd?w=1200",
      "https://images.unsplash.com/photo-1528909514045-2fa4ac7a08ba?w=1200",
    ],
  },
  {
    "host_email": "yuki@example.com",
    "category_slug": "trending",
    "title": "Camden Canal Loft",
    "description": "Industrial loft overlooking the canal market — music and markets on your doorstep.",
    "property_type": PropertyType.APARTMENT,
    "price_per_night": 17800,
    "cleaning_fee": 6000,
    "country": "United Kingdom",
    "city": "London",
    "state": None,
    "address": "5 Regent's Canal Path",
    "lat": 51.5416,
    "lng": -0.1460,
    "max_guests": 4,
    "bedrooms": 2,
    "beds": 2,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "kitchen", "washer", "tv"],
    "images": [
      "https://images.unsplash.com/photo-1533929736458-ca588d08c8cd?w=1200",
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200",
    ],
  },
  {
    "host_email": "emma@example.com",
    "category_slug": "countryside",
    "title": "Hampstead Heath Cottage",
    "description": "Leafy north London cottage steps from the Heath ponds and village cafes.",
    "property_type": PropertyType.HOUSE,
    "price_per_night": 24000,
    "cleaning_fee": 8000,
    "country": "United Kingdom",
    "city": "London",
    "state": None,
    "address": "11 Flask Walk",
    "lat": 51.5560,
    "lng": -0.1780,
    "max_guests": 5,
    "bedrooms": 3,
    "beds": 3,
    "bathrooms": 2,
    "amenity_slugs": ["wifi", "kitchen", "fireplace", "free-parking", "washer", "patio"],
    "images": [
      "https://images.unsplash.com/photo-1605276374104-dee2c83ff4c8?w=1200",
      "https://images.unsplash.com/photo-1600047509358-9dc75507daeb?w=1200",
    ],
  },
  # --- Rome ---
  {
    "host_email": "marco@example.com",
    "category_slug": "trending",
    "title": "Trastevere Courtyard Flat",
    "description": "Cobblestone charm, ivy courtyard, and trattorias on every corner.",
    "property_type": PropertyType.APARTMENT,
    "price_per_night": 15500,
    "cleaning_fee": 5000,
    "country": "Italy",
    "city": "Rome",
    "state": None,
    "address": "Via della Lungaretta 42",
    "lat": 41.8893,
    "lng": 12.4695,
    "max_guests": 4,
    "bedrooms": 2,
    "beds": 2,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "kitchen", "air-conditioning", "washer"],
    "images": [
      "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1200",
      "https://images.unsplash.com/photo-1529260830199-42c24126f198?w=1200",
    ],
  },
  {
    "host_email": "sarah@example.com",
    "category_slug": "omg",
    "title": "Vatican View Penthouse",
    "description": "Rooftop terrace facing St. Peter's dome — golden hour is unforgettable.",
    "property_type": PropertyType.APARTMENT,
    "price_per_night": 32000,
    "cleaning_fee": 11000,
    "country": "Italy",
    "city": "Rome",
    "state": None,
    "address": "Via della Conciliazione 8",
    "lat": 41.9022,
    "lng": 12.4583,
    "max_guests": 5,
    "bedrooms": 2,
    "beds": 3,
    "bathrooms": 2,
    "amenity_slugs": ["wifi", "kitchen", "air-conditioning", "patio", "tv", "washer"],
    "images": [
      "https://images.unsplash.com/photo-1531572753322-ad063cecc140?w=1200",
      "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=1200",
    ],
  },
  {
    "host_email": "emma@example.com",
    "category_slug": "mansions",
    "title": "Piazza Navona Palazzo Suite",
    "description": "High ceilings, frescoed details, and fountain views from the salon.",
    "property_type": PropertyType.APARTMENT,
    "price_per_night": 39000,
    "cleaning_fee": 14000,
    "country": "Italy",
    "city": "Rome",
    "state": None,
    "address": "Piazza Navona 15",
    "lat": 41.8992,
    "lng": 12.4731,
    "max_guests": 6,
    "bedrooms": 3,
    "beds": 4,
    "bathrooms": 2,
    "amenity_slugs": ["wifi", "kitchen", "air-conditioning", "washer", "dryer", "tv"],
    "images": [
      "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1200",
      "https://images.unsplash.com/photo-1555993539-1732b0258235?w=1200",
    ],
  },
  {
    "host_email": "yuki@example.com",
    "category_slug": "countryside",
    "title": "Monti Artist's Atelier",
    "description": "Light-filled atelier between the Colosseum and boutique Monti streets.",
    "property_type": PropertyType.APARTMENT,
    "price_per_night": 14000,
    "cleaning_fee": 4500,
    "country": "Italy",
    "city": "Rome",
    "state": None,
    "address": "Via dei Serpenti 20",
    "lat": 41.8947,
    "lng": 12.4903,
    "max_guests": 3,
    "bedrooms": 1,
    "beds": 2,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "kitchen", "workspace", "air-conditioning"],
    "images": [
      "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=1200",
      "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=1200",
    ],
  },
  {
    "host_email": "marco@example.com",
    "category_slug": "beachfront",
    "title": "Testaccio Market Loft",
    "description": "Foodie loft above the market — cook local produce in a chef's kitchen.",
    "property_type": PropertyType.APARTMENT,
    "price_per_night": 13500,
    "cleaning_fee": 4500,
    "country": "Italy",
    "city": "Rome",
    "state": None,
    "address": "Via Galvani 54",
    "lat": 41.8765,
    "lng": 12.4750,
    "max_guests": 4,
    "bedrooms": 2,
    "beds": 2,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "kitchen", "washer", "tv"],
    "images": [
      "https://images.unsplash.com/photo-1455587734955-081b22074882?w=1200",
      "https://images.unsplash.com/photo-1560448204-61dc36dc98c8?w=1200",
    ],
  },
  # --- Malibu ---
  {
    "host_email": "sarah@example.com",
    "category_slug": "beachfront",
    "title": "Point Dume Beach Cottage",
    "description": "Sandy toes cottage with outdoor shower and bluff trails nearby.",
    "property_type": PropertyType.HOUSE,
    "price_per_night": 32000,
    "cleaning_fee": 12000,
    "country": "United States",
    "city": "Malibu",
    "state": "California",
    "address": "29000 Cliffside Dr",
    "lat": 34.0025,
    "lng": -118.8050,
    "max_guests": 5,
    "bedrooms": 2,
    "beds": 3,
    "bathrooms": 2,
    "amenity_slugs": ["wifi", "kitchen", "free-parking", "beach-access", "patio", "bbq-grill"],
    "images": [
      "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=1200",
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200",
    ],
  },
  {
    "host_email": "emma@example.com",
    "category_slug": "amazing-pools",
    "title": "Malibu Hills Infinity Escape",
    "description": "Canyon views, infinity pool, and starry nights above PCH.",
    "property_type": PropertyType.VILLA,
    "price_per_night": 65000,
    "cleaning_fee": 22000,
    "country": "United States",
    "city": "Malibu",
    "state": "California",
    "address": "4000 Rambla Pacifico",
    "lat": 34.0380,
    "lng": -118.6900,
    "max_guests": 10,
    "bedrooms": 5,
    "beds": 6,
    "bathrooms": 5,
    "amenity_slugs": ["wifi", "kitchen", "pool", "hot-tub", "free-parking", "gym", "bbq-grill", "patio"],
    "images": [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200",
    ],
  },
  {
    "host_email": "marco@example.com",
    "category_slug": "lakefront",
    "title": "Carbon Beach Modern",
    "description": "Glass-box modern on Carbon Beach — open plan living for sunset dinners.",
    "property_type": PropertyType.HOUSE,
    "price_per_night": 72000,
    "cleaning_fee": 25000,
    "country": "United States",
    "city": "Malibu",
    "state": "California",
    "address": "22102 Pacific Coast Hwy",
    "lat": 34.0250,
    "lng": -118.7000,
    "max_guests": 8,
    "bedrooms": 4,
    "beds": 5,
    "bathrooms": 4,
    "amenity_slugs": ["wifi", "kitchen", "beach-access", "air-conditioning", "washer", "dryer", "tv", "patio"],
    "images": [
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=1200",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200",
    ],
  },
  {
    "host_email": "yuki@example.com",
    "category_slug": "cabins",
    "title": "Malibu Canyon A-Frame",
    "description": "Cozy A-frame tucked in the canyon — hiking trails and hot cocoa nights.",
    "property_type": PropertyType.CABIN,
    "price_per_night": 21000,
    "cleaning_fee": 7000,
    "country": "United States",
    "city": "Malibu",
    "state": "California",
    "address": "3200 Malibu Canyon Rd",
    "lat": 34.0600,
    "lng": -118.7005,
    "max_guests": 4,
    "bedrooms": 2,
    "beds": 2,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "kitchen", "fireplace", "free-parking", "patio"],
    "images": [
      "https://images.unsplash.com/photo-1449844908441-882987f99fa1?w=1200",
      "https://images.unsplash.com/photo-1518780664697-55e3abf8446b?w=1200",
    ],
  },
  {
    "host_email": "sarah@example.com",
    "category_slug": "beachfront",
    "title": "Zuma Dunes Guest Suite",
    "description": "Private suite steps from Zuma Beach with surfboards and beach chairs.",
    "property_type": PropertyType.GUESTHOUSE,
    "price_per_night": 18500,
    "cleaning_fee": 6000,
    "country": "United States",
    "city": "Malibu",
    "state": "California",
    "address": "30000 Broad Beach Rd",
    "lat": 34.0155,
    "lng": -118.8200,
    "max_guests": 3,
    "bedrooms": 1,
    "beds": 2,
    "bathrooms": 1,
    "amenity_slugs": ["wifi", "kitchen", "beach-access", "free-parking", "air-conditioning"],
    "images": [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200",
      "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=1200",
    ],
  },
]

# Bookings reference listing title, guest email, dates as ISO strings, status.
BOOKINGS = [
  {
    "listing_title": "Historic Apartment near the Colosseum",
    "guest_email": "alex@example.com",
    "check_in": "2026-06-10",
    "check_out": "2026-06-15",
    "guests": 2,
    "status": BookingStatus.COMPLETED,
    "with_review": True,
    "review_rating": 5,
    "review_comment": "Perfect location and Marco was an incredible host. Would stay again!",
  },
  {
    "listing_title": "Oceanview Retreat with Private Deck",
    "guest_email": "jamie@example.com",
    "check_in": "2026-08-12",
    "check_out": "2026-08-16",
    "guests": 4,
    "status": BookingStatus.CONFIRMED,
    "with_review": False,
  },
  {
    "listing_title": "Minimalist Studio in Shibuya",
    "guest_email": "chris@example.com",
    "check_in": "2026-09-20",
    "check_out": "2026-09-25",
    "guests": 1,
    "status": BookingStatus.CONFIRMED,
    "with_review": False,
  },
  {
    "listing_title": "Georgian Townhouse in Notting Hill",
    "guest_email": "alex@example.com",
    "check_in": "2026-05-01",
    "check_out": "2026-05-06",
    "guests": 6,
    "status": BookingStatus.COMPLETED,
    "with_review": True,
    "review_rating": 4,
    "review_comment": "Beautiful home in a great neighborhood. Minor noise from the street at night.",
  },
  {
    "listing_title": "Tuscan Villa with Olive Grove",
    "guest_email": "jamie@example.com",
    "check_in": "2026-10-15",
    "check_out": "2026-10-22",
    "guests": 8,
    "status": BookingStatus.PENDING,
    "with_review": False,
  },
  {
    # Pending checkout demo for primary guest (alex) — id 6 after seed
    "listing_title": "Modern Loft in the Mission",
    "guest_email": "alex@example.com",
    "check_in": "2026-11-08",
    "check_out": "2026-11-12",
    "guests": 2,
    "status": BookingStatus.PENDING,
    "with_review": False,
  },
  {
    # Past completed stay for jamie so Leave a review demos cleanly
    "listing_title": "Canggu Rice-Field Bungalow",
    "guest_email": "jamie@example.com",
    "check_in": "2026-06-01",
    "check_out": "2026-06-05",
    "guests": 2,
    "status": BookingStatus.COMPLETED,
    "with_review": False,
  },
]

WISHLISTS = [
  {"user_email": "alex@example.com", "listing_title": "Lake Como Waterfront Villa"},
  {"user_email": "alex@example.com", "listing_title": "Santorini Cave House"},
  {"user_email": "jamie@example.com", "listing_title": "Bali Jungle Villa with Pool"},
  {"user_email": "chris@example.com", "listing_title": "Treehouse in the Redwoods"},
  {"user_email": "chris@example.com", "listing_title": "Hakone Mountain Cabin"},
]
